- name: Expense setup
  hosts: all
  become: yes
  tasks:
    - name: install the nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    
    - name: start nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted